config/routes.rb
Rails.application.routes.draw do
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  
  patch 'users/:id/', to: 'users#update'
  
  resources :users, only: [:show, :new, :create] do
    member do
      get :followings
      get :followers
    end
    
    collection do
      get 'users/:id/edit', to: 'users#edit'
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :first_name, presence: true, length: { maximum: 50 }
  validates :last_name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
                    
  has_secure_password

  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  

  
  
  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user

  def counts(user)
    @count_followings = user.followings.count
    @count_followers = user.followers.count
  end
  
  def set_current_user
    @current_user ||= current_user
  end
  
  def current_user
    return @current_user if @current_user
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end
  helper_method :current_user
end

app/controllers/edit_controller.rb
class EditController < ApplicationController
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :require_user_logged_in

  def create
    user = User.find(params[:follow_id])
    current_user.follow(user)
    flash[:success] = 'ユーザをフォローしました。'
    redirect_to user
  end

  def destroy
    user = User.find(params[:follow_id])
    current_user.unfollow(user)
    flash[:success] = 'ユーザのフォローを解除しました。'
    redirect_to user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'LOG IN'
      redirect_to @user
    else
      flash.now[:danger] = 'Failed Log in'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'LOG OUT'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'PROFILE has changed'
      redirect_to @user
    else
      flash.now[:danger] = 'PROFILE error'
      render :edit
    end
  end
  
    
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings.page(params[:page])
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers.page(params[:page])
    counts(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :phone_number, :date_of_birth, :live, :state, :profile_photo_img, :profile_content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_url(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}&d=mp"
  end
end

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="text-center text-muted"></div>
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-left" href="/"><img src="/images/logo.png" alt="NEOTRIP"></a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="gravatar">
                  <img src="<%= gravatar_url(current_user, size: 20) %>" alt="" class="img-circle">
                </span>
                <%= current_user.first_name %>
                <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li>
                  <%= link_to 'PROFILE', user_path(current_user) %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                  <%= link_to 'MESSAGE', messages_path %>
                </li>
                <li role="separator" class="divider"></li>
                <li>
                <li><%= link_to 'LOG OUT', logout_path, method: :delete %></li>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'SIGN UP', signup_path %></li>
            <li><%= link_to 'LOG IN', login_path %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>Neotrip</title>
    <%= csrf_meta_tags %>
    

    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- app/assets/stylesheets -->
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <!-- app/assets/javascripts-->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Bootstrap JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= favicon_link_tag %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield :cover %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_for(current_user.relationships.build) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/create.html.erb
<h1>Relationships#create</h1>
<p>Find me in app/views/relationships/create.html.erb</p>

app/views/relationships/destroy.html.erb
<h1>Relationships#destroy</h1>
<p>Find me in app/views/relationships/destroy.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/edit.html.erb
<h1><% @user %>EDIT USER / ユーザー編集 </h1>

<%= form_for(@user) do |f| %>

  <div class="form-group">
    <%= f.label :live, "Country / 移住国" %><br>
    <%= f.select :live, [["Australia", "australia"], ["Canada", "canada"], ["Japan", "japan"]],class:"form-control" %>
  </div>
  
  <div class="form-group">
    <%= f.label :state, "State / 都道府県" %><br>
    <%= f.select :state, [["Australia", "australia"], ["Canada", "canada"], ["Japan", "japan"]],class:"form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :profile_content, "Profile / 自己紹介" %><br>
    <%= f.text_area :profile_content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :profile_photo_img, "User photo / ユーザー画像" %><br>
    <%= f.file_field :profile_photo_img, class: 'form-control' %>
  </div>


  <%= f.submit 'SUBMIT' %>
<% end %>

<%= link_to 'BACK', user_path %>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <div class="col-xs-8">
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>Followings <span class="badge"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>Followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-xs-offset-3 col-xs-6">
    <div class="panel panel-default">
      <div class="panel-heading">Register / 会員登録</div>
      <div class="panel-body">
        <%= form_for(@user) do |f| %>
          <div class="form-group">
            <%= f.label :first_name, 'First name / 名' %>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :last_name, 'Last name / 性' %>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :email, 'E-mail' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :phone_number, 'Phone number / 電話番号' %>
            <%= f.phone_field :phone_number, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :date_of_birth, 'Date of birth / 誕生日' %>
            <%= f.date_field :date_of_birth, class: 'form-control' %>
          </div>
          
          <div class="form-group">
            <%= f.label :live, "Country / 移住国" %><br>
            <%= f.select :live, [["Australia", "australia"], ["Canada", "canada"], ["Japan", "japan"]],class:"form-control" %>
          </div>
          
          <div class="form-group">
            <%= f.label :state, "State / 都道府県" %><br>
            <%= f.select :state, [["Australia", "australia"], ["Canada", "canada"], ["Japan", "japan"]],class:"form-control" %>
          </div>


          <div class="form-group">
            <%= f.label :password, 'Password' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password_confirmation, 'Password' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <div class="text-center">
            <%= f.submit 'SUBMIT / 登録', class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="name text-center">
    USER NAME : <%= @user.first_name %>
  </div>

  <div class="follow" >
    <%= render 'relationships/follow_button', user: @user %>
    <ul class="nav nav-tabs nav-justified">
      <li class="<%= 'active' if current_page?(followings_user_path(@user)) %>"><%= link_to followings_user_path(@user) do %>following <span class="btn"><%= @count_followings %></span><% end %></li>
      <li class="<%= 'active' if current_page?(followers_user_path(@user)) %>"><%= link_to followers_user_path(@user) do %>followers <span class="badge"><%= @count_followers %></span><% end %></li>
    </ul>
  </div>
  
  <div class="icon text-left">
  <img src="<%= gravatar_url(@user, size: 150) %>" alt="" class="img-square">
  </div>
  
  <div class= "edit text-center">
    <%= link_to 'EDIT / 編集', {:controller => :users, :action => :edit} %>
  </div>
  
  <div class="profile text-center">
    PROFILE / 自己紹介<br>
    <%= @user.profile_content %>
  </div>
  
  <div class="live text-left">
    COUNTRY<br>
    <%= @user.live %>
  </div>
  <br>
  <div class="state text-left">
    STATE<br>
    <%= @user.state %>
  </div>
  